// Code generated by hertz generator.

package douyin_service

import (
	"context"
	"fmt"

	core "simple_douyin/biz/model/core"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Feed .
// @router douyin/feed [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core.DouyinFeedRequest
	err = c.BindAndValidate(&req)

	fmt.Printf("Feed: %+v\n", req)

	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// resp := new(core.DouyinFeedResponse)
	resp := &core.DouyinFeedResponse{
		StatusCode: 1,
		StatusMsg:  "test",
		VideoList:  nil,
		NextTime:   2,
	}

	c.JSON(consts.StatusOK, resp)
}
